/**
 * SANSINOZ SWIMMING CLUB - Initial Mock Data
 */

const INITIAL_CLASSES = [
  {
    id: 'cls-1',
    namaKelas: 'Kelas Pemula (Basic Swim & Fundamentals)',
    kodeRoom: 'ROOM-101',
    ruangPembagian: 'Room Alpha - Area Kolam Dangkal & Lintasan 1',
    headCoach: 'Coach Agus Supriatna',
    fotoCoachUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    asistenCoach: 'Coach Rian',
    fokusLatihan: 'Pengenalan air, pernapasan, teknik dasar gaya bebas & gaya dada, keberanian',
    jadwalLatihan: 'Senin, Rabu, Jumat (15:30 - 17:00 WIB)',
    kapasitasMaksimal: 20,
    keterangan: 'Khusus atlet pemula usia di bawah 10 tahun atau yang baru bergabung.',
  },
  {
    id: 'cls-2',
    namaKelas: 'Kelas Junior Sprint (25m & 50m Specialization)',
    kodeRoom: 'ROOM-202',
    ruangPembagian: 'Room Bravo - Kolam Sprint (Lintasan 2 & 3)',
    headCoach: 'Coach Ryan Hidayat',
    fotoCoachUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    asistenCoach: 'Coach Anita',
    fokusLatihan: 'Kecepatan reaksi start, eksplosivitas sprint 25m & 50m, cadence kayuhan',
    jadwalLatihan: 'Selasa, Kamis, Sabtu (15:30 - 17:30 WIB)',
    kapasitasMaksimal: 18,
    keterangan: 'Fokus persiapan kejuaraan lintasan pendek 25m & 50m KU IV & KU III.',
  },
  {
    id: 'cls-3',
    namaKelas: 'Kelas Development (KU III & KU II Development)',
    kodeRoom: 'ROOM-303',
    ruangPembagian: 'Room Charlie - Kolam Utama (Lintasan 4 & 5)',
    headCoach: 'Coach Maya Indah, S.Pd.',
    fotoCoachUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    asistenCoach: 'Coach Diki',
    fokusLatihan: 'Penguatan 4 gaya renang, efisiensi flip turn, aerobic endurance 100m/200m',
    jadwalLatihan: 'Senin s/d Sabtu (16:00 - 18:00 WIB)',
    kapasitasMaksimal: 15,
    keterangan: 'Fokus pengembangan teknik bertahap menuju limit waktu kejuaraan daerah.',
  },
  {
    id: 'cls-4',
    namaKelas: 'Kelas High Performance (Elite & Target Limit)',
    kodeRoom: 'ROOM-404',
    ruangPembagian: 'Room Delta - Olympic Deep Pool (Lintasan 6, 7, 8)',
    headCoach: 'Coach Doni Setiawan, M.Or.',
    fotoCoachUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    asistenCoach: 'Coach Farhan',
    fokusLatihan: 'Target Limit Waktu Kualifikasi, intensitas VO2Max, mental tanding, analisis underwater video',
    jadwalLatihan: 'Senin s/d Sabtu (Subuh 05:00 - 07:00 & Sore 16:00 - 18:30 WIB)',
    kapasitasMaksimal: 12,
    keterangan: 'Tim utama tanding kejuaraan tingkat utama & seleksi daerah.',
  },
];

const INITIAL_ATHLETES = [
  {
    id: 'atl-1',
    nis: 'SNZ-2024-001',
    nama: 'M. Rizky Pratama',
    gender: 'Laki-Laki',
    tanggalLahir: '2011-05-14',
    kelompokUmur: 'KU II (14-15 thn)',
    kelasId: 'cls-4',
    headCoach: 'Coach Doni Setiawan, M.Or.',
    namaWali: 'Bpk. Hendra Pratama',
    kontakWali: '0812-3456-7890',
    fotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    tanggalBergabung: '2022-01-10',
    status: 'Aktif',
    tinggiBadanCm: 168,
    beratBadanKg: 58,
  },
  {
    id: 'atl-2',
    nis: 'SNZ-2024-002',
    nama: 'Siti Nur Aisyah',
    gender: 'Perempuan',
    tanggalLahir: '2012-08-22',
    kelompokUmur: 'KU III (12-13 thn)',
    kelasId: 'cls-2',
    headCoach: 'Coach Ryan Hidayat',
    namaWali: 'Ibu Rahmawati',
    kontakWali: '0813-9876-5432',
    fotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    tanggalBergabung: '2023-03-15',
    status: 'Aktif',
    tinggiBadanCm: 154,
    beratBadanKg: 44,
  },
  {
    id: 'atl-3',
    nis: 'SNZ-2024-003',
    nama: 'Kenzo Putra Sansinoz',
    gender: 'Laki-Laki',
    tanggalLahir: '2015-11-03',
    kelompokUmur: 'KU IV (<11 thn)',
    kelasId: 'cls-2',
    headCoach: 'Coach Ryan Hidayat',
    namaWali: 'Bpk. Budi Santoso',
    kontakWali: '0857-1122-3344',
    fotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    tanggalBergabung: '2023-08-01',
    status: 'Aktif',
    tinggiBadanCm: 138,
    beratBadanKg: 32,
  },
  {
    id: 'atl-4',
    nis: 'SNZ-2024-004',
    nama: 'Nabila Zahra Khairunnisa',
    gender: 'Perempuan',
    tanggalLahir: '2010-02-18',
    kelompokUmur: 'KU I (16-18 thn)',
    kelasId: 'cls-4',
    headCoach: 'Coach Doni Setiawan, M.Or.',
    namaWali: 'Bpk. Ahmad Fauzi',
    kontakWali: '0821-4455-6677',
    fotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    tanggalBergabung: '2021-06-01',
    status: 'Aktif',
    tinggiBadanCm: 163,
    beratBadanKg: 52,
  },
  {
    id: 'atl-5',
    nis: 'SNZ-2024-005',
    nama: 'Farel Danendra',
    gender: 'Laki-Laki',
    tanggalLahir: '2013-09-09',
    kelompokUmur: 'KU III (12-13 thn)',
    kelasId: 'cls-3',
    headCoach: 'Coach Maya Indah, S.Pd.',
    namaWali: 'Ibu Dewita',
    kontakWali: '0819-8877-6655',
    fotoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    tanggalBergabung: '2023-01-20',
    status: 'Aktif',
    tinggiBadanCm: 150,
    beratBadanKg: 42,
  },
  {
    id: 'atl-6',
    nis: 'SNZ-2024-006',
    nama: 'Alya Kirana',
    gender: 'Perempuan',
    tanggalLahir: '2016-04-12',
    kelompokUmur: 'KU IV (<11 thn)',
    kelasId: 'cls-1',
    headCoach: 'Coach Agus Supriatna',
    namaWali: 'Bpk. Surya Kurnia',
    kontakWali: '0812-7788-9900',
    fotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    tanggalBergabung: '2024-02-10',
    status: 'Aktif',
    tinggiBadanCm: 132,
    beratBadanKg: 28,
  }
];

const INITIAL_TIME_RECORDS = [
  {
    id: 'tr-1',
    athleteId: 'atl-1',
    stroke: 'Gaya Bebas',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 25.80,
    timeFormatted: '25.80',
    tanggal: '2026-07-15',
    namaAjang: 'Time Trial Internal Sansinoz',
    catatan: 'Rekor Personal Best baru. Streamline sangat rapi.',
    isPersonalBest: true,
  },
  {
    id: 'tr-2',
    athleteId: 'atl-1',
    stroke: 'Gaya Bebas',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 26.40,
    timeFormatted: '26.40',
    tanggal: '2026-05-10',
    namaAjang: 'Kejurda Jawa Barat',
    catatan: 'Meraih Medali Perak',
  },
  {
    id: 'tr-3',
    athleteId: 'atl-1',
    stroke: 'Gaya Bebas',
    distance: '25m',
    poolLength: '25m',
    timeInSeconds: 12.10,
    timeFormatted: '12.10',
    tanggal: '2026-06-20',
    namaAjang: 'Sprint Trial Sansinoz',
    isPersonalBest: true,
  },
  {
    id: 'tr-4',
    athleteId: 'atl-1',
    stroke: 'Gaya Kupu-Kupu',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 27.50,
    timeFormatted: '27.50',
    tanggal: '2026-07-01',
    namaAjang: 'Time Trial Internal Sansinoz',
    isPersonalBest: true,
  },
  {
    id: 'tr-5',
    athleteId: 'atl-2',
    stroke: 'Gaya Bebas',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 29.10,
    timeFormatted: '29.10',
    tanggal: '2026-07-15',
    namaAjang: 'Time Trial Internal Sansinoz',
    isPersonalBest: true,
    catatan: 'Lolos Limit Nasional KU III',
  },
  {
    id: 'tr-6',
    athleteId: 'atl-2',
    stroke: 'Gaya Dada',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 37.80,
    timeFormatted: '37.80',
    tanggal: '2026-06-12',
    namaAjang: 'Kejuaraan Antar Klub Sansinoz Cup',
    isPersonalBest: true,
  },
  {
    id: 'tr-7',
    athleteId: 'atl-2',
    stroke: 'Gaya Bebas',
    distance: '25m',
    poolLength: '25m',
    timeInSeconds: 13.90,
    timeFormatted: '13.90',
    tanggal: '2026-07-10',
    namaAjang: 'Sprint Trial Sansinoz',
    isPersonalBest: true,
  },
  {
    id: 'tr-8',
    athleteId: 'atl-3',
    stroke: 'Gaya Bebas',
    distance: '25m',
    poolLength: '25m',
    timeInSeconds: 15.20,
    timeFormatted: '15.20',
    tanggal: '2026-07-15',
    namaAjang: 'Sprint Trial Sansinoz',
    isPersonalBest: true,
    catatan: 'Sangat cepat untuk KU IV',
  },
  {
    id: 'tr-9',
    athleteId: 'atl-3',
    stroke: 'Gaya Bebas',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 33.40,
    timeFormatted: '33.40',
    tanggal: '2026-06-25',
    namaAjang: 'Time Trial Internal Sansinoz',
    isPersonalBest: true,
  },
  {
    id: 'tr-10',
    athleteId: 'atl-3',
    stroke: 'Gaya Punggung',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 38.90,
    timeFormatted: '38.90',
    tanggal: '2026-05-18',
    namaAjang: 'Krappsi Jabar',
    isPersonalBest: true,
  },
  {
    id: 'tr-11',
    athleteId: 'atl-4',
    stroke: 'Gaya Bebas',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 26.50,
    timeFormatted: '26.50',
    tanggal: '2026-07-18',
    namaAjang: 'Time Trial Internal Sansinoz',
    isPersonalBest: true,
    catatan: 'Tembus Limit Nasional KU I',
  },
  {
    id: 'tr-12',
    athleteId: 'atl-4',
    stroke: 'Gaya Dada',
    distance: '100m',
    poolLength: '50m',
    timeInSeconds: 76.20,
    timeFormatted: '01:16.20',
    tanggal: '2026-06-05',
    namaAjang: 'Kejurda Jawa Barat',
    isPersonalBest: true,
  },
  {
    id: 'tr-13',
    athleteId: 'atl-5',
    stroke: 'Gaya Dada',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 36.90,
    timeFormatted: '36.90',
    tanggal: '2026-07-12',
    namaAjang: 'Time Trial Internal Sansinoz',
    isPersonalBest: true,
  },
  {
    id: 'tr-14',
    athleteId: 'atl-5',
    stroke: 'Gaya Bebas',
    distance: '50m',
    poolLength: '50m',
    timeInSeconds: 29.80,
    timeFormatted: '29.80',
    tanggal: '2026-06-30',
    namaAjang: 'Time Trial Internal Sansinoz',
    isPersonalBest: true,
  }
];

const INITIAL_MEDALS = [
  {
    id: 'med-1',
    athleteId: 'atl-1',
    kejuaraan: 'Kejurda Jawa Barat 2026',
    tanggal: '2026-05-10',
    stroke: 'Gaya Bebas',
    distance: '50m',
    kelompokUmur: 'KU II (14-15 thn)',
    medali: 'Emas',
    catatanWaktu: '25.80',
  },
  {
    id: 'med-2',
    athleteId: 'atl-1',
    kejuaraan: 'Kejurda Jawa Barat 2026',
    tanggal: '2026-05-11',
    stroke: 'Gaya Kupu-Kupu',
    distance: '50m',
    kelompokUmur: 'KU II (14-15 thn)',
    medali: 'Perak',
    catatanWaktu: '27.50',
  },
  {
    id: 'med-3',
    athleteId: 'atl-4',
    kejuaraan: 'Kejuaraan Antar Klub Nasional 2026',
    tanggal: '2026-04-18',
    stroke: 'Gaya Bebas',
    distance: '50m',
    kelompokUmur: 'KU I (16-18 thn)',
    medali: 'Emas',
    catatanWaktu: '26.50',
  },
  {
    id: 'med-4',
    athleteId: 'atl-2',
    kejuaraan: 'Krappsi Jabar 2026',
    tanggal: '2026-06-12',
    stroke: 'Gaya Dada',
    distance: '50m',
    kelompokUmur: 'KU III (12-13 thn)',
    medali: 'Emas',
    catatanWaktu: '37.80',
  },
  {
    id: 'med-5',
    athleteId: 'atl-3',
    kejuaraan: 'Krappsi Jabar 2026',
    tanggal: '2026-06-12',
    stroke: 'Gaya Bebas',
    distance: '25m',
    kelompokUmur: 'KU IV (<11 thn)',
    medali: 'Perak',
    catatanWaktu: '15.20',
  },
  {
    id: 'med-6',
    athleteId: 'atl-5',
    kejuaraan: 'Sansinoz Swim Cup 2026',
    tanggal: '2026-03-20',
    stroke: 'Gaya Dada',
    distance: '50m',
    kelompokUmur: 'KU III (12-13 thn)',
    medali: 'Perunggu',
    catatanWaktu: '36.90',
  }
];

const INITIAL_EVALUATIONS = [
  {
    id: 'eval-1',
    athleteId: 'atl-1',
    tanggalEvaluasi: '2026-07-25',
    kehadiranPersen: 96,
    skorStamina: 92,
    teknikStartReaction: 9,
    teknikFlipTurn: 9,
    enduranceRating: 'Luar Biasa',
    catatanCoach: 'Perkembangan luar biasa pada dorongan kaki gaya bebas. Start reaction time rata-rata 0.62 detik.',
    targetBerikutnya: 'Menembus batas 25.00 detik pada 50m gaya bebas di Kejurnas mendatang.',
  },
  {
    id: 'eval-2',
    athleteId: 'atl-2',
    tanggalEvaluasi: '2026-07-22',
    kehadiranPersen: 92,
    skorStamina: 85,
    teknikStartReaction: 8,
    teknikFlipTurn: 8,
    enduranceRating: 'Sangat Baik',
    catatanCoach: 'Ritme napas gaya dada makin stabil. Perlu pertahankan fleksibilitas pergelangan kaki.',
    targetBerikutnya: 'Sharpening waktu 50m Gaya Dada menuju < 36.50 detik.',
  },
  {
    id: 'eval-3',
    athleteId: 'atl-3',
    tanggalEvaluasi: '2026-07-20',
    kehadiranPersen: 90,
    skorStamina: 82,
    teknikStartReaction: 8,
    teknikFlipTurn: 7,
    enduranceRating: 'Baik',
    catatanCoach: 'Kedisiplinan tinggi di kelas Sprint. Underwater kick sudah jauh berkembang pesat.',
    targetBerikutnya: 'Optimalkan 3 kayuhan pertama setelah breakout start.',
  }
];

const INITIAL_BMI_LOGS = [
  {
    id: 'bmi-1',
    athleteId: 'atl-1',
    tanggal: '2026-07-01',
    tinggiCm: 168,
    beratKg: 58,
    bmiValue: 20.5,
    kategori: 'Ideal Atlet Renang',
    catatanGizi: 'Massa otot sangat ideal untuk perenang sprint KU II. Lanjutkan asupan protein tinggi pasca-latihan.',
    aiRecommendation: {
      saranLangkah: 'Pertahankan rasio massa otot & stamina atlet dengan evaluasi rutin setiap 2 minggu dan istirahat yang cukup.',
      nutrisiGizi: 'Karbohidrat kompleks 2 jam sebelum latihan (oatmeal, pisang) & 25-30g protein (dada ayam, telur, susu) dalam 30 menit pasca renang.',
      jenisOlahraga: 'Latihan dryland explosive power (box jumps, medicine ball slam, core plank) 2-3x seminggu untuk dorongan start & turn.',
      analisisAI: 'Rasio BMI 20.5 sangat proporsional untuk perenang gaya bebas. Kombinasi massa otot dan daya apung di air sangat optimal untuk mengurangi hambatan hidrodinamis.',
      tanggalDibuat: '2026-07-01'
    }
  },
  {
    id: 'bmi-2',
    athleteId: 'atl-2',
    tanggal: '2026-07-01',
    tinggiCm: 154,
    beratKg: 44,
    bmiValue: 18.6,
    kategori: 'Ideal Atlet Renang',
    catatanGizi: 'Tinggi dan berat seimbang. Pertahankan karbohidrat kompleks sebelum sesi latihan sore.',
    aiRecommendation: {
      saranLangkah: 'Jaga konsistensi berat badan agar tidak turun ke kategori kurus saat periode volume latihan mingguan tinggi.',
      nutrisiGizi: 'Tingkatkan asupan kalori bersih dengan lemak sehat (alpukat, kacang-kacangan), smoothie buah, dan susu pemulihan pasca renang.',
      jenisOlahraga: 'Latihan penguatan otot bahu dan core dengan resistance band (rotator cuff & latissimus dorsi) untuk menambah power kayuhan.',
      analisisAI: 'BMI 18.6 berada pada batas ideal bawah. Diperlukan penyesuaian porsi nutrisi agar otot tidak mengalami pemecahan (katabolisme) saat sesi endurance.',
      tanggalDibuat: '2026-07-01'
    }
  },
  {
    id: 'bmi-3',
    athleteId: 'atl-3',
    tanggal: '2026-07-01',
    tinggiCm: 138,
    beratKg: 32,
    bmiValue: 16.8,
    kategori: 'Kurus',
    catatanGizi: 'Perlu penambahan nutrisi protein dan susu tinggi kalsium untuk menunjang pertumbuhan tinggi badan KU IV.',
    aiRecommendation: {
      saranLangkah: 'Targetkan penambahan berat badan bertahap (+1 hingga 1.5 kg per bulan) dengan program gizi surplus kalori & pengawasan coach.',
      nutrisiGizi: 'Pola makan 5-6x sehari (3 makan utama + 2-3 snack tinggi protein seperti telur rebus, keju, pisang, & susu pertumbuhan kalsium tinggi).',
      jenisOlahraga: 'Latihan fisik dasar akuatik (kickboard drills, streamline glide) & dryland bodyweight (push-up ringan, squat) untuk stimulasi kepadatan tulang.',
      analisisAI: 'Status BMI 16.8 (Kurus) berpotensi mengurangi daya apung (buoyancy) dan daya tahan stamina pada lintasan 50m. Diperlukan penambahan massa otot & lemak tubuh sehat.',
      tanggalDibuat: '2026-07-01'
    }
  }
];

const INITIAL_USER_ACCOUNTS = [
  {
    id: 'usr-01',
    name: 'Coach Data Renang (Head Coach)',
    email: 'datarenang2023@gmail.com',
    password: 'coachpass2026',
    accessKey: 'KEY-HEADCOACH-777',
    role: 'Head Coach Utama',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    status: 'Aktif',
    tanggalDibuat: '2026-01-10',
  },
  {
    id: 'usr-02',
    name: 'Admin Management Sansinoz',
    email: 'admin@sansinoz.com',
    password: 'adminpass2026',
    accessKey: 'KEY-ADMIN-999',
    role: 'Administrator Club',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    status: 'Aktif',
    tanggalDibuat: '2026-01-10',
  },
  {
    id: 'usr-03',
    name: 'Coach Ryan Hidayat',
    email: 'coach@sansinoz.com',
    password: 'coachpass2026',
    accessKey: 'KEY-COACH-888',
    role: 'Head Coach Utama',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    status: 'Aktif',
    tanggalDibuat: '2026-01-15',
  },
  {
    id: 'usr-04',
    name: 'Bpk. Hendra (Wali Atlet Rizky)',
    email: 'orangtua@sansinoz.com',
    password: 'walipass2026',
    accessKey: 'KEY-WALI-123',
    role: 'Orang Tua / Atlet',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    status: 'Aktif',
    tanggalDibuat: '2026-02-01',
  },
  {
    id: 'usr-05',
    name: 'Ibu Ratna (Wali Atlet Aisyah)',
    email: 'wali@sansinoz.com',
    password: 'walipass2026',
    accessKey: 'KEY-WALI-456',
    role: 'Orang Tua / Atlet',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    status: 'Aktif',
    tanggalDibuat: '2026-02-05',
  }
];

const INITIAL_ALFATIH_CONFIG = {
  namaEkskul: 'Ekskul Renang & Pembinaan Aquatics Al-Fatih',
  sekolah: 'Sekolah Al-Fatih',
  limitKapasitas: 30,
  guruPendamping: 'Coach Andri',
  jadwalEkskul: 'Setiap Hari Sabtu (08:00 - 10:00 WIB)',
  lokasiKolam: 'Kolam Renang Sansinoz Utama (Lintasan Khusus Al-Fatih)',
};

const INITIAL_ALFATIH_STUDENTS = [
  {
    id: 'alfatih-1',
    nisn: '0123456781',
    nama: 'Muhammad Umar Al-Fatih',
    kelasSekolah: 'Kelas 5 Al-Khawarizmi',
    gender: 'Laki-Laki',
    namaOrangTua: 'Bpk. Abdullah',
    kontakOrangTua: '0812-1122-3344',
    fotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    medali: {
      emas: 2,
      perak: 1,
      perunggu: 0,
      daftar: [
        { id: 'm-1', jenis: 'Emas', kejuaraan: 'Kejuaraan Renang Al-Fatih 2026', nomorLomba: '25m Gaya Bebas Putra' },
        { id: 'm-2', jenis: 'Emas', kejuaraan: 'Kejuaraan Renang Al-Fatih 2026', nomorLomba: '25m Gaya Dada Putra' },
        { id: 'm-3', jenis: 'Perak', kejuaraan: 'Fun Swim Aquatics 2026', nomorLomba: '25m Gaya Punggung Putra' }
      ]
    },
    statusCapaian25m: {
      gayaBebas: true,
      gayaDada: true,
      gayaPunggung: true,
      gayaKupu: false,
    },
    waktu25m: {
      gayaBebas: '00:22.45',
      gayaDada: '00:26.10',
      gayaPunggung: '00:28.30',
      gayaKupu: '-',
    },
    penilaian: {
      mengapung: 'A',
      menendang: 'A',
      gerakanTangan: 'B',
      teknikBernapas: 'A',
      tanganGayaBebas: 'A',
      kakiGayaBebas: 'A',
      target25mBebas: 'A',
      target25mDada: 'B',
      target25mPunggung: 'B',
      target25mKupu: 'C',
      predikatAkhir: 'A',
      catatanGuru: 'Sudah sangat percaya diri mengapung dan berenang 25m gaya bebas & dada dengan lancar.',
    },
    tanggalMulai: '2026-01-10',
  },
  {
    id: 'alfatih-2',
    nisn: '0123456782',
    nama: 'Aisyah Humaira',
    kelasSekolah: 'Kelas 4 Al-Farabi',
    gender: 'Perempuan',
    namaOrangTua: 'Ibu Siti Aminah',
    kontakOrangTua: '0813-5566-7788',
    fotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    medali: {
      emas: 1,
      perak: 0,
      perunggu: 1,
      daftar: [
        { id: 'm-4', jenis: 'Emas', kejuaraan: 'Kejuaraan Renang Al-Fatih 2026', nomorLomba: '25m Gaya Dada Putri' },
        { id: 'm-5', jenis: 'Perunggu', kejuaraan: 'Fun Swim Aquatics 2026', nomorLomba: '25m Gaya Bebas Putri' }
      ]
    },
    statusCapaian25m: {
      gayaBebas: true,
      gayaDada: true,
      gayaPunggung: false,
      gayaKupu: false,
    },
    waktu25m: {
      gayaBebas: '00:25.80',
      gayaDada: '00:28.15',
      gayaPunggung: '-',
      gayaKupu: '-',
    },
    penilaian: {
      mengapung: 'A',
      menendang: 'B',
      gerakanTangan: 'B',
      teknikBernapas: 'B',
      tanganGayaBebas: 'B',
      kakiGayaBebas: 'B',
      target25mBebas: 'A',
      target25mDada: 'B',
      target25mPunggung: 'C',
      target25mKupu: 'D',
      predikatAkhir: 'B',
      catatanGuru: 'Target 25m Gaya Bebas dan Gaya Dada tuntas. Tingkatkan latihan pernapasan gaya punggung.',
    },
    tanggalMulai: '2026-01-15',
  },
  {
    id: 'alfatih-3',
    nisn: '0123456783',
    nama: 'Ibrahim Rayyan',
    kelasSekolah: 'Kelas 3 Al-Ghazali',
    gender: 'Laki-Laki',
    namaOrangTua: 'Bpk. Ridwan',
    kontakOrangTua: '0815-9900-1122',
    fotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    statusCapaian25m: {
      gayaBebas: true,
      gayaDada: false,
      gayaPunggung: false,
      gayaKupu: false,
    },
    waktu25m: {
      gayaBebas: '00:29.40',
      gayaDada: '-',
      gayaPunggung: '-',
      gayaKupu: '-',
    },
    penilaian: {
      mengapung: 'B',
      menendang: 'B',
      gerakanTangan: 'C',
      teknikBernapas: 'C',
      tanganGayaBebas: 'B',
      kakiGayaBebas: 'B',
      target25mBebas: 'B',
      target25mDada: 'C',
      target25mPunggung: 'D',
      target25mKupu: 'D',
      predikatAkhir: 'C',
      catatanGuru: 'Berhasil mencapai target 25m gaya bebas. Perlu penguatan kayuhan tangan dan teknik bernapas.',
    },
    tanggalMulai: '2026-02-01',
  },
];

const DEFAULT_LIMIT_STANDARDS = [
  // 25m Freestyle
  { stroke: 'Gaya Bebas', distance: '25m', kelompokUmur: 'KU IV (<11 thn)', gender: 'Laki-Laki', limitTargetSeconds: 15.50, limitClubSeconds: 16.50 },
  { stroke: 'Gaya Bebas', distance: '25m', kelompokUmur: 'KU IV (<11 thn)', gender: 'Perempuan', limitTargetSeconds: 16.20, limitClubSeconds: 17.20 },
  { stroke: 'Gaya Bebas', distance: '25m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Laki-Laki', limitTargetSeconds: 13.80, limitClubSeconds: 14.80 },
  { stroke: 'Gaya Bebas', distance: '25m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Perempuan', limitTargetSeconds: 14.50, limitClubSeconds: 15.50 },
  
  // 50m Freestyle
  { stroke: 'Gaya Bebas', distance: '50m', kelompokUmur: 'KU IV (<11 thn)', gender: 'Laki-Laki', limitTargetSeconds: 32.50, limitClubSeconds: 34.50 },
  { stroke: 'Gaya Bebas', distance: '50m', kelompokUmur: 'KU IV (<11 thn)', gender: 'Perempuan', limitTargetSeconds: 34.00, limitClubSeconds: 36.00 },
  { stroke: 'Gaya Bebas', distance: '50m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Laki-Laki', limitTargetSeconds: 28.50, limitClubSeconds: 30.00 },
  { stroke: 'Gaya Bebas', distance: '50m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Perempuan', limitTargetSeconds: 29.80, limitClubSeconds: 31.50 },
  { stroke: 'Gaya Bebas', distance: '50m', kelompokUmur: 'KU II (14-15 thn)', gender: 'Laki-Laki', limitTargetSeconds: 26.20, limitClubSeconds: 27.50 },
  { stroke: 'Gaya Bebas', distance: '50m', kelompokUmur: 'KU II (14-15 thn)', gender: 'Perempuan', limitTargetSeconds: 28.00, limitClubSeconds: 29.20 },
  { stroke: 'Gaya Bebas', distance: '50m', kelompokUmur: 'KU I (16-18 thn)', gender: 'Laki-Laki', limitTargetSeconds: 24.80, limitClubSeconds: 25.80 },
  { stroke: 'Gaya Bebas', distance: '50m', kelompokUmur: 'KU I (16-18 thn)', gender: 'Perempuan', limitTargetSeconds: 26.90, limitClubSeconds: 27.90 },

  // 50m Breaststroke
  { stroke: 'Gaya Dada', distance: '50m', kelompokUmur: 'KU IV (<11 thn)', gender: 'Laki-Laki', limitTargetSeconds: 41.50, limitClubSeconds: 43.50 },
  { stroke: 'Gaya Dada', distance: '50m', kelompokUmur: 'KU IV (<11 thn)', gender: 'Perempuan', limitTargetSeconds: 43.00, limitClubSeconds: 45.00 },
  { stroke: 'Gaya Dada', distance: '50m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Laki-Laki', limitTargetSeconds: 36.00, limitClubSeconds: 38.00 },
  { stroke: 'Gaya Dada', distance: '50m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Perempuan', limitTargetSeconds: 38.20, limitClubSeconds: 40.00 },
  { stroke: 'Gaya Dada', distance: '50m', kelompokUmur: 'KU II (14-15 thn)', gender: 'Laki-Laki', limitTargetSeconds: 32.80, limitClubSeconds: 34.50 },
  { stroke: 'Gaya Dada', distance: '50m', kelompokUmur: 'KU II (14-15 thn)', gender: 'Perempuan', limitTargetSeconds: 35.50, limitClubSeconds: 37.00 },

  // 50m Butterfly
  { stroke: 'Gaya Kupu-Kupu', distance: '50m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Laki-Laki', limitTargetSeconds: 30.20, limitClubSeconds: 32.00 },
  { stroke: 'Gaya Kupu-Kupu', distance: '50m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Perempuan', limitTargetSeconds: 32.50, limitClubSeconds: 34.00 },
  { stroke: 'Gaya Kupu-Kupu', distance: '50m', kelompokUmur: 'KU II (14-15 thn)', gender: 'Laki-Laki', limitTargetSeconds: 27.90, limitClubSeconds: 29.50 },
  { stroke: 'Gaya Kupu-Kupu', distance: '50m', kelompokUmur: 'KU II (14-15 thn)', gender: 'Perempuan', limitTargetSeconds: 30.10, limitClubSeconds: 31.80 },

  // 50m Backstroke
  { stroke: 'Gaya Punggung', distance: '50m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Laki-Laki', limitTargetSeconds: 33.00, limitClubSeconds: 35.00 },
  { stroke: 'Gaya Punggung', distance: '50m', kelompokUmur: 'KU III (12-13 thn)', gender: 'Perempuan', limitTargetSeconds: 35.20, limitClubSeconds: 37.00 },
  { stroke: 'Gaya Punggung', distance: '50m', kelompokUmur: 'KU II (14-15 thn)', gender: 'Laki-Laki', limitTargetSeconds: 30.50, limitClubSeconds: 32.00 },
  { stroke: 'Gaya Punggung', distance: '50m', kelompokUmur: 'KU II (14-15 thn)', gender: 'Perempuan', limitTargetSeconds: 32.80, limitClubSeconds: 34.50 },
];
